[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "apps/webhook-handler/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock"

[functions]
  directory = "apps/webhook-handler/dist"
  node_bundler = "esbuild"
  included_files = ["apps/webhook-handler/dist/**"]
