name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build, Lint and Test
        run: |
          npm run build
          npm run lint
          npm run test
      
      - name: Publish Packages
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish -w packages/config --access public || true
          npm publish -w packages/core --access public || true
          npm publish -w apps/cli --access public || true
          npm publish -w apps/webhook-handler --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 